# Generated by Django 4.1.5 on 2023-01-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_user_phone_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
