# Generated by Django 4.1.5 on 2023-01-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("desctiption", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("installTime", models.IntegerField()),
                ("timesBought", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
