# Generated by Django 4.1.5 on 2023-01-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="desctiption",
            new_name="description",
        ),
    ]
