# Generated by Django 4.1.5 on 2023-01-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tag", "0001_initial"),
        ("Product", "0003_favourites"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, to="Tag.tag"),
        ),
    ]
