# Generated by Django 4.1.5 on 2023-01-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="placeholder_product.jpg", null=True, upload_to=""
                    ),
                ),
                ("is_first", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-is_first", "created"],
            },
        ),
    ]
