# Generated by Django 4.1.5 on 2023-01-12 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0002_rename_desctiption_product_description"),
        ("Image", "0004_alter_productimage_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="productID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="Product.product",
            ),
        ),
    ]
