# Generated by Django 4.1.5 on 2023-01-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0003_favourites"),
        ("Image", "0005_alter_productimage_productid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductImage",
            new_name="Image",
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["-is_first", "created"]},
        ),
        migrations.RenameField(
            model_name="image",
            old_name="productID",
            new_name="product",
        ),
    ]
